### ISSUE TITLE
FR16: Item Confirmation

### ISSUE THREAD

**Issue by k-odonnell** [WSU-4110/My-Digital-Closet#16]
|FR|
|---|
|**Goal**:  Each time a user uploads an item of clothing, the app will display a confirmation message that the item has been successfully saved.
**Stakeholders:** Users|
| **Description:** Once an item is added and saved to the app, a message indicating that the item was successfully saved will appear to indicate that the user can now apply that item to any of their outfits. Conversely, if there’s any issue with the image such as poor image quality or storage issues, they will receive a message based on the error and the proper steps to fix the issue.|
| **Origin:** My Digital Closet members came up with this during our second SRS meeting.|
| **Version:** 2.0  |  
|**Date:** 1/31/23 
|  **Priority:**  3|

**Comment by NickZuke** [comment]
Completed for Sprint 3
