### ISSUE TITLE
NR1: Photo Capacity

### ISSUE THREAD

**Issue by k-odonnell** [WSU-4110/My-Digital-Closet#17]
|NR1|
|---|
|**Goal**: The app will be able to store up to 100 photos of clothing items uploaded by the user
**Stakeholders:** Users, investors|
| **Description:** The database for the app must be able to store up to 100 photo pieces uploaded by each user. The system should be designed in a way that it can accommodate an increasing number of photos as needed, ensuring seamless scalability. This will allow the app to handle an increasing number of users and the data they generate, without sacrificing performance or stability.|
| **Origin:** My Digital Closet Team members came up with this idea during our first SRS meeting when discussing feasible storage limits of the app.|
| **Version:** 1.0  |  
|**Date:** 1/29/23 
|  **Priority:**  1|

**Comment by NickZuke** [comment]
Finished for Sprint 3
